### ISSUE TITLE
License string should be SPDX id

### ISSUE THREAD

**Issue by chennes** [Giraut/freecad_streamdeck_addon#2]
https://github.com/Giraut/freecad_streamdeck_addon/blob/3e5903bbaac8ace79cef7b15414142677e09de54/package.xml#L8

This should be "GPL-3.0-or-later" -- the Addon Manager expects a [SPDX license identifier](https://spdx.org/licenses/).

**Comment by Giraut** [comment]
This was generated by the developer tool in the FreeCAD addon manager itself upon parsing my local repo. Should I open an issue in the FreeCAD repo about it?

**Comment by chennes** [comment]
No need to file an issue, I fixed it a couple of weeks ago. Thanks!
